# Generated by Django 4.1 on 2022-08-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='drzwi',
            field=models.TextField(default='5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produkt',
            name='kolor',
            field=models.TextField(default='Red'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produkt',
            name='silnik',
            field=models.TextField(default='Diesel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produkt',
            name='skrzynia',
            field=models.TextField(default='Manualna'),
        ),
    ]
