# Generated by Django 4.1 on 2022-08-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0003_alter_produkt_nazwa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='kolor',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='silnik',
            field=models.CharField(max_length=120),
        ),
    ]
