# Generated by Django 4.1 on 2022-08-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0004_alter_produkt_kolor_alter_produkt_silnik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='cena',
            field=models.DecimalField(decimal_places=2, max_digits=1000000),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='drzwi',
            field=models.DecimalField(decimal_places=0, max_digits=1),
        ),
    ]
