# Generated by Django 4.1 on 2022-08-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0005_alter_produkt_cena_alter_produkt_drzwi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='opis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
