# Generated by Django 4.1 on 2022-08-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0011_remove_produkt_opis'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='opis',
            field=models.TextField(default='opis'),
            preserve_default=False,
        ),
    ]
