# Generated by Django 4.1.1 on 2022-10-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='colour',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
